# Generated by Django 5.0.4 on 2025-04-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_classgroup_tournament_match_tournamentparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
