# Generated by Django 5.0.4 on 2025-04-21 18:00

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessbot',
            name='file_path',
            field=models.FileField(upload_to=users.utils.PathAndRename(), validators=[users.utils.validate_file_size, users.utils.validate_file_extension]),
        ),
    ]
